### ISSUE TITLE
Cyclic dependency error

### ISSUE THREAD

**Issue by wladimiiir** [marcelklehr/toposort#20]
Latest release causes:
`Error: Cyclic dependency: "[object Object]"
    at visit (/app/node_modules/toposort/index.js:32:13)
    at visit (/app/node_modules/toposort/index.js:48:9)
    at Function.toposort [as array] (/app/node_modules/toposort/index.js:25:22)
    at Object.module.exports.dependency (/app/node_modules/html-webpack-plugin/lib/chunksorter.js:55:19)
    at HtmlWebpackPlugin.sortChunks (/app/node_modules/html-webpack-plugin/index.js:347:33)
    at Compiler.<anonymous> (/app/node_modules/html-webpack-plugin/index.js:72:19)
    at Compiler.applyPluginsAsyncSeries (/app/node_modules/tapable/lib/Tapable.js:206:13)
    at Compiler.emitAssets (/app/node_modules/webpack/lib/Compiler.js:308:7)
    at onCompiled (/app/node_modules/webpack/lib/Compiler.js:247:11)
    at /app/node_modules/webpack/lib/Compiler.js:499:13
    at next (/app/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/app/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/app/node_modules/tapable/lib/Tapable.js:206:13)
    at /app/node_modules/webpack/lib/Compiler.js:496:10
    at Compilation.applyPluginsAsyncSeries (/app/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/app/node_modules/webpack/lib/Compilation.js:649:19)
    at Compilation.applyPluginsAsyncSeries (/app/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/app/node_modules/webpack/lib/Compilation.js:640:11)
    at next (/app/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/app/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:230:5)
    at next (/app/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/app/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:230:5)
    at Compilation.applyPluginsAsyncSeries (/app/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/app/node_modules/webpack/lib/Compilation.js:635:10)
    at next (/app/node_modules/tapable/lib/Tapable.js:202:11)
    at ExtractTextPlugin.<anonymous> (/app/node_modules/extract-text-webpack-plugin/index.js:345:4)
    at Compilation.applyPluginsAsyncSeries (/app/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/app/node_modules/webpack/lib/Compilation.js:631:9)
    at next (/app/node_modules/tapable/lib/Tapable.js:202:11)
    at ExtractTextPlugin.<anonymous> (/app/node_modules/extract-text-webpack-plugin/index.js:317:5)`

Let me know if you need more information ;)

**Comment by xzilja** [comment]
`throw new Error('Cyclic dependency: '+JSON.stringify(node))` and followed by same output as above.

Not much changed in terms of environment that this is ran in, hence pinpointing it down to latest release

**Comment by jety91** [comment]
+1

**Comment by die214144031** [comment]
+1

**Comment by seanlandsman** [comment]
For me too - the fix on my side was to downgrade the version of toposort to 1.0.4.

I didn't actually reference this dependency directly - webpack does - just fyi.

**Comment by hstaniszewski** [comment]
+1

**Comment by IljaDaderko** [comment]
@seanlandsman I think webpack is whats failing us as well, how did you downgrade toposort for it specifically? Never did it before for specific packages, would be cool to know :)

**Comment by clubajax** [comment]
I'm using yarn, and added this to my package.json:
```
"resolutions": {
	"toposort": "1.0.4"
}
```

**Comment by aPoCoMiLogin** [comment]
```npm install toposort@1.0.4```

**Comment by evanjmg** [comment]
+1

**Comment by GurpreetSran** [comment]
+1

**Comment by justboras** [comment]
+1

**Comment by Yantrio** [comment]
We're also hitting this. :(

**Comment by philjones88** [comment]
+1 not too happy, respect semver! :(

**Comment by seanlandsman** [comment]
@IljaDaderko I added this to package.json

"toposort":"1.0.4"

thanks

**Comment by hlodver** [comment]
+1

**Comment by timwoodart** [comment]
+1

**Comment by kasparasg** [comment]
+1

**Comment by marcelklehr** [comment]
I'm so sorry folks. v1.0.6 is out now, which reverts https://github.com/marcelklehr/toposort/pull/19

**Comment by sergiix** [comment]
+1

**Comment by hpwilliams** [comment]
Thanks for quick turnaround!

**Comment by apphelpyulongs** [comment]
thanks for the quick fix. Our production build failed yesterday since it's the dependency of html-webpack-plugin

**Comment by adityavm** [comment]
I'm currently hitting this error in 1.0.6 too (through `html-webpack-plugin`).

```
> npm list toposort
rekrn@1.0.0 <path>
└─┬ webpack-config-basic-dev@2.0.0-0
  └─┬ html-webpack-plugin@3.2.0
    └── toposort@1.0.6
```

I made a new and clean repo to try and reproduce it but wasn't able to:

```
> npm list toposort
testwebpack4@1.0.0 <path>
└─┬ webpack-config-basic-dev@2.0.0-0
  └─┬ html-webpack-plugin@3.2.0
    └── toposort@1.0.6
```

Any help will be appreciated.

**Comment by marcelklehr** [comment]
Sorry for my absence. Can you reproduce this with toposort only? Alternatively, what does the dependency graph look like?

**Comment by marcelklehr** [comment]
So, when I run the build script for the reproduction repo, I get the following edges of the dependency graph:

```
5005 => 5004,
5003 => 5004,
5004 => 5005,
5003 => 5005
```

Clearly, there is a cyclic dependency between 5005 and 5004. The only "bug" in toposort, is the type error, if you will, which I'll fix now. :)

**Comment by sumbad** [comment]
@WiseBird I found that error happiness if html-webpack-plugin uses default chunksSortMode parameter. 
For example, you can change it in the following way:

```
new HtmlWebpackPlugin({
     "template": "./src/index.html",
     "filename": "./index.html",
     "hash": false,
     "inject": true,
     "compile": true,
     "favicon": false,
     "minify": false,
     "cache": true,
     "showErrors": true,
     "chunks": "all",
     "excludeChunks": [],
     "title": "Webpack App",
     "xhtml": true,
     "chunksSortMode": 'none'
   }
 }),
```

Or use your special function. For example:
```
const entryPoints = ["inline","polyfills","sw-register","styles","vendor","main"];
...
chunksSortMode: function sort(left, right) {
  let leftIndex = entryPoints.indexOf(left.names[0]);
  let rightIndex = entryPoints.indexOf(right.names[0]);
  if (leftIndex > rightIndex) {
      return 1;
  }
  else if (leftIndex < rightIndex) {
      return -1;
  }
  else {
      return 0;
  }
}
...
```

**Comment by laurentpayot** [comment]
> I found that error happiness if html-webpack-plugin uses default chunksSortMode parameter.

@sumbad  do you mean that this cyclic dependency error **does not** occur when `chunksSortMode` option of HtmlWebpackPlugin is set to `'none'`?
If that's what you mean then it's the same for me since I switched to webpack 4.

Should we open an HtmlWebpackPlugin issue?

**Comment by marcelklehr** [comment]
@laurentpayot there already is one: https://github.com/jantimon/html-webpack-plugin/issues/870 ;)

**Comment by smxyzb** [comment]
> @WiseBird I found that error happiness if html-webpack-plugin uses default chunksSortMode parameter.
> For example, you can change it in the following way:
> 
> ```
> new HtmlWebpackPlugin({
>      "template": "./src/index.html",
>      "filename": "./index.html",
>      "hash": false,
>      "inject": true,
>      "compile": true,
>      "favicon": false,
>      "minify": false,
>      "cache": true,
>      "showErrors": true,
>      "chunks": "all",
>      "excludeChunks": [],
>      "title": "Webpack App",
>      "xhtml": true,
>      "chunksSortMode": 'none'
>    }
>  }),
> ```
> Or use your special function. For example:
> 
> ```
> const entryPoints = ["inline","polyfills","sw-register","styles","vendor","main"];
> ...
> chunksSortMode: function sort(left, right) {
>   let leftIndex = entryPoints.indexOf(left.names[0]);
>   let rightIndex = entryPoints.indexOf(right.names[0]);
>   if (leftIndex > rightIndex) {
>       return 1;
>   }
>   else if (leftIndex < rightIndex) {
>       return -1;
>   }
>   else {
>       return 0;
>   }
> }
> ...
> ```
厉害了我的哥

**Comment by soulofmischief** [comment]
I also get this error without specifying `chunksSortMode` as `none`.

**Comment by denov** [comment]
i'm seeing this error with 1.0.7 in a dojo project

```
$ npm list toposort
project@1.0.0 C:\development\projects\xxx\project
`-- @dojo/cli-build-app@5.0.3
  `-- html-webpack-plugin@3.2.0
    `-- toposort@1.0.7

```

change `chucksSortMode` to `none` fixes it

**Comment by vindyala** [comment]
> @WiseBird I found that error happiness if html-webpack-plugin uses default chunksSortMode parameter.
> For example, you can change it in the following way:
> 
> ```
> new HtmlWebpackPlugin({
>      "template": "./src/index.html",
>      "filename": "./index.html",
>      "hash": false,
>      "inject": true,
>      "compile": true,
>      "favicon": false,
>      "minify": false,
>      "cache": true,
>      "showErrors": true,
>      "chunks": "all",
>      "excludeChunks": [],
>      "title": "Webpack App",
>      "xhtml": true,
>      "chunksSortMode": 'none'
>    }
>  }),
> ```
> 
> Or use your special function. For example:
> 
> ```
> const entryPoints = ["inline","polyfills","sw-register","styles","vendor","main"];
> ...
> chunksSortMode: function sort(left, right) {
>   let leftIndex = entryPoints.indexOf(left.names[0]);
>   let rightIndex = entryPoints.indexOf(right.names[0]);
>   if (leftIndex > rightIndex) {
>       return 1;
>   }
>   else if (leftIndex < rightIndex) {
>       return -1;
>   }
>   else {
>       return 0;
>   }
> }
> ...
> ```

yes, change to chucksSortMode to none in webpack config file fixes it
